import os

os.remove("axelspringer-hosts")

hostsfile = open("axelspringer-hosts", "w+")

hostsfile.write("# This is an autogenerated file by ./generate_hostfile.py with the files \"www-hostnames\" and \"hostnames\"\n\n")

wwwhostnames = open("www-hostnames", "r")

for line in wwwhostnames.readlines():
    if (line[0] == "\n" or line[0] == "#"):
        continue
    hostsfile.write("0.0.0.0 " + line)
    if (line[-1] != "\n"):
        hostsfile.write("\n")
    hostsfile.write("0.0.0.0 www." + line)
    if (line[-1] != "\n"):
        hostsfile.write("\n")

hostsfile.write("\n")
wwwhostnames.close()

hostnames = open("hostnames", "r")

for line in hostnames.readlines():
    if (line[0] == "\n" or line[0] == "#"):
        continue
    hostsfile.write("0.0.0.0 " + line)
    if (line[-1] != "\n"):
        hostsfile.write("\n")

hostnames.close()
hostsfile.flush()
hostsfile.close()
